export const Articles = new Map<string, string>([
  [ "人机对战", "https://www.wulihub.com.cn/gc/WkBVKE/index.html" ],
  [ "行为准则", "https://mp.weixin.qq.com/s/ZLni07m1O1-sohd5Fs4gQA" ],
  [ "收纳", "https://mp.weixin.qq.com/s/_MYPFB1DTw1XD9eNgo8BfQ" ],
  [ "多人对战", "https://mp.weixin.qq.com/s/xNaJBKCoYhqAeB899U3HHA" ],
  [ "黑白卡组", "https://mp.weixin.qq.com/s/hcTFVU1JlrGoAGoJxSyvLQ" ],
  [ "人机牌组", "https://mp.weixin.qq.com/s/_rlPAWt2HE5PKGJJkljMbQ" ],
  [ "NRDB", "https://mp.weixin.qq.com/s/95YCtrJFk5z6lkdyhXgtBw" ],
  [ "组织比赛", "https://mp.weixin.qq.com/s/UQauB85tG4TyvVKE4mOmVw" ],
  [ "网络对战", "https://mp.weixin.qq.com/s/8au_l-JPlrKY4TqE0RtiDw" ],
  [ "时序详解", "https://mp.weixin.qq.com/s/eRa_Ed6ccqrBRZ0Z03LQtA" ],
  [ "新手指南", "https://mp.weixin.qq.com/s/JanueWj4dCh9QakqyQNbjA" ],
  [ "派系特色", "https://mp.weixin.qq.com/s/1dPhNbltPl8TlhU6IGBFnw" ],
  [ "前世今生", "https://mp.weixin.qq.com/s/hyZ7i9aE71C_nJZvV_fByg" ],
  [ "亚克力", "https://mp.weixin.qq.com/s/yfBl2Q4Tt1ignU5HEJ--nQ" ],
  [ "比赛软件", "https://mp.weixin.qq.com/s/sxgVP8843iQ0V9ZVtJIkUA" ],
  [ "入坑指南", "https://mp.weixin.qq.com/s/avyNlbsP8qF-LTjL92GDXA" ],
  [ "游戏介绍", "https://mp.weixin.qq.com/s/z4rol59Yukcp49q2npM3sQ" ],
  [ "理牌/理牌须知/仰望理牌", "https://mp.weixin.qq.com/s/aiby31JSexEueLv7O6ZQqA" ],
  [ "新手牌组", "https://mp.weixin.qq.com/s/BnAktusfIpPJILgXms7xgw" ],
  [ "新手教学", "https://mp.weixin.qq.com/s/jMIQ1hoEcfNouL7Lkqcrag" ],
  [ "新人必看", "https://mp.weixin.qq.com/s/_DXv9RjAOJ5P0Fdo1g0G8g" ],
]);
